### ISSUE TITLE
MAC Address Lookup Failed on Windows

### ISSUE THREAD

**Issue by DefinitlyEvil** [libp2p/go-netroute#28]
```go
		if bytes.Equal(iface.HardwareAddr, ifRow.PhysAddr[:]) {
			return &iface
		}
```
Code above had error because `ifRow.PhysAddr` has code: 
```go
PhysAddr        [MAXLEN_PHYSADDR]byte
```
and `MAXLEN_PHYSADDR` is set by `const MAXLEN_PHYSADDR = 8`. 

In my case, the last two bytes needs to be removed, thus: 
```go
iface.HardwareAddr, ifRow.PhysAddr[:6]
```

**Comment by p-shahi** [comment]
Right a MAC address is 6 bytes in all cases. @DefinitlyEvil I'm not familiar with this code, is the function you're referencing only supposed to return the MAC address interface?
Perhaps @willscott can help instruct whether you should create a PR.

**Comment by willscott** [comment]
this looks like https://github.com/libp2p/go-netroute/blob/master/netroute_windows.go#L201 

both of these buffers have been created by the windows system calls.

capping the prefix as you do with `ifRow.PhysAddr[:6]` seems like a good answer - probably worth wrapping that in a check that the length of `ifRow.PhysAddr` is at least 6 to make sure there isn't an array-out-bounds when doing so.

PR welcome!

**Comment by willscott** [comment]
@DefinitlyEvil 
Do you know what the final 2 bytes of the `ifRow.PhysAddr` are / why `const MAXLEN_PHYSADDR = 8`?

**Comment by maxosprojects** [comment]
@willscott please review https://github.com/libp2p/go-netroute/pull/29

Please let me know if you'd like me to make any changes to the PR.

Thank you!

**Comment by DefinitlyEvil** [comment]
Hi, sorry for long response. 

@willscott Golang runtime seemed to have some bugs that caused the length to be 8. 
@maxosprojects Thanks for the patch! <3 

Cheers!
