### ISSUE TITLE
Incorrect IPv4 route returned

### ISSUE THREAD

**Issue by inputvalidation** [libp2p/go-netroute#50]
I'm on macOS 13.7 and am using a VPN application that sets the following routes (to route everything through the VPN tunnel):

```
Destination        Gateway            Flags           Netif Expire
0/1                10.11.12.13        UGScg           utun3
default            192.168.1.1        UGScg             en0
default            link#28            UCSIg       bridge100      !
128.0/1            10.11.12.13        UGSc            utun3
```

... if I inspect the routing table with `route`, the expected route is shown (the mask is slightly puzzling...):

```
% route get 8.8.8.8
   route to: dns.google
destination: default
       mask: 128.0.0.0
    gateway: 10.11.12.13
  interface: utun3
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING,GLOBAL>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0
```

... however, the route returned by `netroute` is not the same:

```go
        r, err := netroute.New()
        if err != nil {
                return fmt.Errorf("cannot create netroute: %w", err)
        }

        // Get route to Google DNS
        iface, gw, _, err := r.Route(net.IPv4(8, 8, 8, 8))
        if err != nil {
                return fmt.Errorf("cannot get route: %w", err)
        }

        fmt.Printf("%+v\n", iface)
        fmt.Println(gw)
```

```
&{Index:28 MTU:1500 Name:bridge100 HardwareAddr:c0:ff:ee:c0:ff:ee Flags:up|broadcast|multicast|running}
<nil>
```

**Comment by willscott** [comment]
Interesting, it's hard to understand what would cause the library to pick that route given that it's
(a) less specific than the 2 set by your VPN
and
(b) has the 'expire: !' flag.

The logic should be getting the VPN interface just on the more specific mask (https://github.com/libp2p/go-netroute/blob/master/common.go#L43 )

Can you print the set of routes that netroute is working with to make it's decision. It would be good to know what the standardized table looks like versus your system route table:
if you print the string format of `r` in your code sample you should get a diagnostic reading of the routing table as netroute sees it: https://github.com/libp2p/go-netroute/blob/master/common.go#L82

**Comment by willscott** [comment]
Can you confirm this issue is resolved with the fix from https://github.com/libp2p/go-netroute/pull/51 ?

**Comment by willscott** [comment]
Not hearing otherwise, i'm going to mark this as fixed by 51 and close until we get more info to the contrary

**Comment by inputvalidation** [comment]
Hi @willscott! Truly appreciate the fix and can confirm this indeed fixes the issue :)

**Comment by inputvalidation** [comment]
> Hi @willscott! Truly appreciate the fix and can confirm this indeed fixes the issue :)

Would this warrant the release of a new version? That would make it easier to include it in my project (I had to figure out how to test a go module on the master version, but have now learned how to do it).

**Comment by willscott** [comment]
yep - was waiting for confirmation. i'll cut a release later today
