### ISSUE TITLE
We shouldn't make assumptions about interface indices

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-netroute#8]
```
    TestRoute: netroute_test.go:12: out of order iface 1 = {6436 1500 eth0 02:42:ac:1c:00:03 up|broadcast|multicast}
```

**Comment by willscott** [comment]
We may not have the privileges to learn all of the local interfaces and addresses - e.g. when we're running in a container. In these cases, it seems best to operate on the assumption that our only local interface addresses are the ones we can see, and if we end up routing to other addresses held on the local machine they'll end up looking the same as other lan-local routes where no other gateway intervenes.

**Comment by Stebalien** [comment]
Links may be in-order, but you can definitely delete links.
